### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int64)) , expected: (tensor(int32))

### ISSUE THREAD

**Issue by cyclonedll** [MNaseerSubhani/Blip-Image-Captioning-Large-ONNX#1]
![QQ图片20240318234122](https://github.com/MNaseerSubhani/Blip-Image-Captioning-Large-ONNX/assets/95995457/5ee3fa90-f59f-43da-8b16-30e96febe3f8)

I changed int64 to int32 , but it said :
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int32)) , expected: (tensor(int64))

I can't figure out the issue.

**Comment by MNaseerSubhani** [comment]
@cyclonedll  which OS you are using to convert?

**Comment by cyclonedll** [comment]
My OS is Win11 22631.3296
torch                            2.0.1+cu118
torchaudio                       2.0.2+cu118
torchvision                      0.15.2+cu118
onnx                             1.15.0
onnxruntime                      1.15.1

**Comment by wxbool** [comment]
I have a similar problem, my environment is: windows 11 

torch 1.13.1
torchvision 0.14.1
onnx 1.13.0
onnxruntime 1.17.3

**Comment by MNaseerSubhani** [comment]
@wxboo Use Colab Instead local libraries.
